blank_issues_enabled: false
contact_links:
  - name: ğŸŒ Get Support from Slack Community
    url: https://join.slack.com/t/dogu-community/shared_invite/zt-1zespy16o-TgYIureSBI6ma6o_nG3gVw
    about: Please ask and answer questions here.
