name: dogu-actions/run-test
description: run test with gamium
author: dogu
inputs:
  # git options
  checkout:
    description: checkout git repository
    default: false
    required: false
  branchOrTag:
    description: branch or tag to checkout
    default: main
    required: false
  clean:
    description: run git clean -fdx before git pull without git clone
    default: true
    required: false
  checkoutPath:
    description: relative path of Dogu routine workspace path or absolute path to checkout
    default: ''
    required: false
  checkoutUrl:
    description: checkout url. if not set, use repository url from Dogu project settings. recommended to use repository url from Dogu project settings.
    default: ''
    required: false

  # app options
  appVersion:
    description: app version to download and install
    default: ''
    required: false
  uninstallApp:
    description: uninstall app before install
    default: false
    required: false

  # test options
  command:
    description: test command
    required: true
runs:
  main: build/src/main.js
