[tool.poetry]
name = "dogu-device-client"
version = "1.2.0rc3"
description = "Dogu's device client to control devices"
authors = ["Dogu Technologies"]
readme = "README.md"
packages = [{ include = "dogu" }]

[tool.poetry.dependencies]
python = "^3.9"
websockets = "11.0.3"
requests = "2.31.0"
dacite = "1.8.1"

[tool.poetry.group.dev.dependencies]
pytest = "7.3.2"
black = "23.3.0"
pylint = "2.17.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pylint.'MESSAGES CONTROL']
max-line-length = 180
disable = """
    missing-module-docstring,
    missing-class-docstring,
    missing-function-docstring,
    broad-exception-raised,
    broad-exception-caught,
    too-few-public-methods,
    unused-argument,
    duplicate-code,
"""
